[package]
name = "bitwarden-secrets-operator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
dirs = "4.0.0"
envy = "0.4.2"
futures = "0.3.27"
k8s-openapi = { version = "0.17.0", features = ["v1_26"] }
kube = { version = "0.78.0", features = ["runtime","derive"] }
lazy_static = "1.4.0"
prometheus = { version = "0.13.3" , features = ["process"] }
schemars = "0.8.12"
serde = "1.0.157"
serde_json = "1.0.94"
serde_yaml = "0.9.19"
thiserror = "1.0.39"
tokio = { version = "1.26", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
rocket = { version = "0.5.0-rc.2" }
chrono = "0.4.24"
