[package]
name = "bitwarden-secrets-operator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
dirs = "5.0.1"
envy = "0.4.2"
futures = "0.3.28"
k8s-openapi = { version = "0.19.0", features = ["v1_26"] }
kube = { version = "0.84.0", default-features = false, features = ["client","rustls-tls","runtime","derive"] }
lazy_static = "1.4.0"
prometheus = { version = "0.13.3" , features = ["process"] }
schemars = "0.8.12"
serde = "1.0.183"
serde_json = "1.0.104"
serde_yaml = "0.9.25"
thiserror = "1.0.44"
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1.38"
tracing-subscriber = "0.3.17"
rocket = { version = "0.5.0-rc.3" }
chrono = "0.4.26"
regex = "1.9.1"
