[package]
name = "bitwarden-secrets-operator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
chrono = "0.4.38"
clap = { version = "4.5.9", features = ["derive", "env"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
dirs = "5.0.1"
futures = "0.3.29"
gethostname = "0.5.0"
k8s-openapi = { version = "0.22.0", features = ["v1_28"] }
kube = { version = "0.92.1", features = ["runtime", "derive"] }
kube-leader-election = "0.33.0"
lazy_static = "1.5.0"
prometheus = { version = "0.13.4" , features = ["process"] }
regex = "1.10.5"
schemars = "0.8.21"
serde = "1.0.204"
serde_json = "1.0.120"
serde_yaml = "0.9.33"
thiserror = "1.0.63"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
