apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-secrets-operator
  namespace: bitwarden-secrets-operator
  labels:
    name: bitwarden-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden-secrets-operator
  template:
    metadata:
      labels:
        app: bitwarden-secrets-operator
    spec:
      serviceAccountName: bitwarden-secrets-operator
      containers:
        - image: ghcr.io/jrcichra/bitwarden-secrets-operator
          # Use this to login to bitwarden for the first time
          # command: ["tail"]
          # args: ["-f", "/dev/null"]
          name: bitwarden-secrets-operator
          resources:
            requests:
              cpu: "20m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /root/.config/Bitwarden CLI
              name: bitwarden
          imagePullPolicy: Always
      volumes:
        - name: bitwarden
          ### CHANGEME
          hostPath:
            path: /gkube/bitwarden
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden-secrets-operator
  namespace: bitwarden-secrets-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitwarden-secrets-operator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["patch", "create", "delete", "list", "watch"]
  - apiGroups: ["jrcichra.dev"]
    resources: ["bitwardensecrets"]
    verbs: ["patch", "create", "delete", "list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bitwarden-secrets-operator
subjects:
  - kind: ServiceAccount
    name: bitwarden-secrets-operator
    namespace: bitwarden-secrets-operator
roleRef:
  kind: ClusterRole
  name: bitwarden-secrets-operator
  apiGroup: rbac.authorization.k8s.io
---

