apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-secrets-operator
  namespace: bitwarden-secrets-operator
  labels:
    name: bitwarden-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden-secrets-operator
  template:
    metadata:
      labels:
        app: bitwarden-secrets-operator
    spec:
      serviceAccountName: bitwarden-secrets-operator
      containers:
        - image: ghcr.io/jrcichra/bitwarden-secrets-operator
          name: bitwarden-secrets-operator
          resources:
            requests:
              cpu: "20m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: ROCKET_ADDRESS
              value: 0.0.0.0
            - name: BW_CLIENTID
              valueFrom:
                secretKeyRef:
                  key: BW_CLIENTID
                  name: bitwarden-credentials
                  optional: false
            - name: BW_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  key: BW_CLIENTSECRET
                  name: bitwarden-credentials
                  optional: false
            - name: BW_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: BW_PASSWORD
                  name: bitwarden-credentials
                  optional: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden-secrets-operator
  namespace: bitwarden-secrets-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitwarden-secrets-operator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["patch", "create", "delete", "list", "watch"]
  - apiGroups: ["jrcichra.dev"]
    resources: ["bitwardensecrets"]
    verbs: ["patch", "create", "delete", "list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bitwarden-secrets-operator
subjects:
  - kind: ServiceAccount
    name: bitwarden-secrets-operator
    namespace: bitwarden-secrets-operator
roleRef:
  kind: ClusterRole
  name: bitwarden-secrets-operator
  apiGroup: rbac.authorization.k8s.io
---

